TESTS += main.c
INC += ../include
INC += ../3pp/subprocess/include
INC += ../3pp/whereami/src
SRC += ../src/traceback.c
SRC += ../3pp/subprocess/src/subprocess.c
SRC += ../3pp/whereami/src/whereami.c

include test.mk
