name: All

on: [push]

jobs:
  build:

    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo hej
