name: All

on: [push]

jobs:
  build:

    strategy:
      max-parallel: 4
      matrix:
        platform: macos-latest
        python-version: [3.7]

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: dddde
      run: cat /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/os/base.h
    - name: Build and run tests
      run: make test
    - name: Build hello world example
      run: make -C examples/hello_world
